### PR TITLE
Mpurcell id editing of the blockchain contract samples

### PR DESCRIPTION
**Pull request by michellepurcell**
Edits to the instructions for creating a base contract source file. 

Some initial restructuring changes that I'd like to run by the SMEs.

### CODE REVIEW

**Comment by michellepurcell** [comment]
@kletkeman 
Hello Kim,
I checked in some structural changes to the instructions for creating the base/foundational .go contract source file from the basic sample. I think the sections like ###The SimpleChaincode struct and ###version.... and so on, should be moved into an ordered list that clearly outlines the steps for creating the contract along with the sample code.
Do you agree with this approach?
Thanks
Michelle

**Comment by kletkeman** [comment]
@michellepurcell Yes, that makes sense to me. Note that @sumanair created and maintains the simple / basic contract and so it makes sense for her to be more deeply involved in the restructuring. I am happy to continue as well, though.

**Comment by michellepurcell** [comment]
@kletkeman
Thanks Kim.

@sumanair 
Please take a look at the above comment about pull request #18 and let me know if you have any comments. Thanks

**Comment by michellepurcell** [comment]
@sumanair
Hello Suma 

I have restyled and restructured the information for the Basic contract sample. Please review and confirm so that I can merge the pull request.
I also edited the Trade Lane readme, which is more conceptual with a lot less information than the Basic sample. Is the information for the Trade Lane sample sufficient enough for customers?
Thanks
Michelle

**Comment by michellepurcell** [comment]
@sumanair 
Hello Suma,
Are you happy with the edits in this pull request? If so, I'd like to merge them today.
Many thanks
Michelle

**Comment by ccorley** [comment]
Hi Michelle,

Suma is out today, but I took a look at your changes.  They are fairly substantial, but I only saw a few minor changes in what I looked at.  I'd like to pull your changes in, then we can go back and make a few minor updates.  I'll do the merge and then take a look at the resulting doc.

Thanks,
Carole

**Pull request merged**
